
name: ddd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REPO_URL: https://github.com/Lienol/openwrt
  REPO_BRANCH: 19.07
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: x86/lienol_bypass.config
  DIY_P1_SH: x86/feed.sh
  DIY_P2_SH: x86/diy_bypass.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai


jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
      
      run: |
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
             echo $DEBIAN_FRONTEND

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
